pipeline {
  agent any
  tools {
    nodejs 'Instalar NodeJS 11.0.0'
  }

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  stages {
    stage('Install dependencies') {
      steps {
        powershell.exe -Command "cd jenkins-tests; npm install"
      }
    }
    stage('Run tests') {
      steps {
        powershell.exe -Command "cd jenkins-tests; npm test"
      }
    }
  }
}
